apiVersion: v1
kind: Service
metadata:
  name: booklore
  namespace: booklore
spec:
  type: NodePort
  selector:
    app: booklore
  ports:
    - port: 6060
      targetPort: 6060
      nodePort: 30606

